python manage.py shell
from django.contrib.auth.models import User
user1=User.objects.create_user('u3')
user2=User.objects.create_user('u4')
from news.models import *
Author.objects.create(user=user1)
Author.objects.create(user=user2)
Category.objects.create(category='Спорт')
Category.objects.create(category='Политика')
Category.objects.create(category='Наука и техника')
Category.objects.create(category='Кино')
A1=Author.objects.get(user=user1)
N=Post.objects.create(author=A1, typ='NW', title='qwe', text='qwe qwe qwe')
C=Category.objects.get(category='Спорт')
N.category.add(C)
C=Category.objects.get(category='Наука и техника')
N.category.add(C)
Ar=Post.objects.create(author=A1, typ='AR', title='qwe', text='hi')
Ar.category.add(C)
Ar=Post.objects.create(author=A1, typ='AR', title='123test', text='qwertyyy')
Ar.category.add(C)
K1=Comment.objects.create(user=user1, text='sdfdsfsdfd', post=Ar)
K2=Comment.objects.create(user=user1, text='fdsf', post=Ar)
K3=Comment.objects.create(user=user1, text='sdfds', post=N)
K4=Comment.objects.create(user=user1, text='fdsfds', post=N)
K1.like()
K2.dislike()
K3.dislike()
K3.dislike()
K4.like()
K4.like()
Ar.like()
Ar.like()
Ar.like()
N.dislike()
N.dislike()
A1.update_rating()
